---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techstorebe-products
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: techstorebe-products
    spec:
      containers:
      - name: techstorebe-products
        image: vaodyssey/techstoredbe-products:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: techstorebe-products
---
apiVersion: v1
kind: Service
metadata:
  name: techstorebe-products
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: techstorebe-products